#!/system/bin/sh
# chmod -R 755 /su/su.d /sbin/supersu/su.d
#
# Systemless Adreno Driver Mounts
# osm0sis @ xda-developers

sumnt=$(find / -maxdepth 2 | grep -E '^/su$|^/sbin/supersu$');

for i in `find $sumnt/vendor -type f | cut -d/ -f3-`; do
  mount -o bind $sumnt/$i /system/$i;
done;

